name: Deploy FlightAI Customer Service

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week6/1-flightai-customer-service
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}