name: Deploy Document Extractor

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week6/3-document-extractor
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}